import Head from 'next/head'
import React from 'react'

interface Props {
    titleName: string
}

function Header({ titleName }: Props) {
    return (
        <Head>
            <title>{titleName}</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon2.ico" />
        </Head>
    )
}

export default Header